# Generated by Django 2.2.13 on 2020-10-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_animal_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='character',
            field=models.CharField(choices=[('A', 'активный'), ('K', 'спокойный')], max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kind',
            field=models.CharField(choices=[('D', 'dogs'), ('C', 'cats'), ('P', 'parrots')], max_length=1),
        ),
    ]
